# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "192.168.66.10"

  config.vm.synced_folder '.', '/vagrant', disabled: true
  # enable if you want to access the repo via a share
  #config.vm.synced_folder './vagrant-git', '/tmp/vagrant-git'

	config.git.add_repo do |rc|
		rc.target = 'https://github.com:Learnosity/vagrant-git.git'
		rc.path = '/tmp/vagrant-git'
		rc.branch = 'master'
		rc.clone_in_host = true
	end
end
